// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbQx7ZRLmHprWOzPx4ZHRg6J1WQxFZr8E',
    appId: '1:300947537635:web:a83e27505d94eefe824fd6',
    messagingSenderId: '300947537635',
    projectId: 'temu-1501c',
    authDomain: 'temu-1501c.firebaseapp.com',
    storageBucket: 'temu-1501c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASRjIzHxnGUbrN_l1vuptPLneRROtfIV8',
    appId: '1:300947537635:android:94d8a7e0d0399a2e824fd6',
    messagingSenderId: '300947537635',
    projectId: 'temu-1501c',
    storageBucket: 'temu-1501c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW-cyly08jYvkoei6rGWtw9-jws8qDerw',
    appId: '1:300947537635:ios:10ed3c67e1cf3e69824fd6',
    messagingSenderId: '300947537635',
    projectId: 'temu-1501c',
    storageBucket: 'temu-1501c.firebasestorage.app',
    iosBundleId: 'com.example.temu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW-cyly08jYvkoei6rGWtw9-jws8qDerw',
    appId: '1:300947537635:ios:10ed3c67e1cf3e69824fd6',
    messagingSenderId: '300947537635',
    projectId: 'temu-1501c',
    storageBucket: 'temu-1501c.firebasestorage.app',
    iosBundleId: 'com.example.temu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbQx7ZRLmHprWOzPx4ZHRg6J1WQxFZr8E',
    appId: '1:300947537635:web:0632a94a2cae395f824fd6',
    messagingSenderId: '300947537635',
    projectId: 'temu-1501c',
    authDomain: 'temu-1501c.firebaseapp.com',
    storageBucket: 'temu-1501c.firebasestorage.app',
  );
}
